### ISSUE TITLE
Can't install on NixOS

### ISSUE THREAD

**Issue by TimofeyAxenov** [Jas-SinghFSU/HyprPanel#303] opened 2024-10-05 17:44 UTC
**Describe the bug**
Gnome.gnome-bluetooth is installed on the system, but when I rebuild home-manager, it gives me this: error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "gnome-bluetooth" at /nix/store/jsq5vlpnicf122vkpk70f6rypljcys0f-source/nix/default.nix:24'

**Expected behavior**
Hyprbar installing

**Desktop (please complete the following information):**
 - Distribution: NixOS 24.05
 - Window Manager/Desktop Environment: Hyprland

**Comment by anotherhadi** [comment] 2024-10-05 19:52
Duplicate of #291

**Closed** 2024-10-06 07:20 UTC
Labels: help wanted, nix
