### ISSUE TITLE
Bug: Setting Monitor Specific does not apply for secondary screen

### ISSUE THREAD

**Issue by F-4Dev** [Jas-SinghFSU/HyprPanel#671] opened 2024-12-30 02:47 UTC
**Describe the bug**
The setting `Configuration > Bar > Workspaces > Monitor Specific` does not apply for my second screen.
I am not entirely sure whether this setting is setting the width of the workspace box but when I turn it on the box gets more width on my second monitor.

monitor 0:
![image](https://github.com/user-attachments/assets/803eb843-1b59-4789-aad9-bef779f602c6)

monitor 1:
![image](https://github.com/user-attachments/assets/e03ecda2-bd2e-48e3-951a-4f4c65ce0b32)

The setting `Hide Unoccupied` feels more like it should be controlling the width. 

This are my icons:
![image](https://github.com/user-attachments/assets/1f4dd1a5-00c0-4281-b1de-d5b68d8e4ef0)

**To Reproduce**
1. enable `Show Workspace Icons`
2. enable `Monitor Specific` 
3. Now the width of the workspace box on the second monitor should be different form the first monitor.

**Expected behavior**
It should look and behave the same on both monitors when the setting `Hide Unoccupied` is turned on.
Like this:
![image](https://github.com/user-attachments/assets/803eb843-1b59-4789-aad9-bef779f602c6)

`Monitor Specific`  should only show the workspace that are present on its monitor.

**Screenshots**
added above

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
-

**Comment by davfsa** [comment] 2024-12-30 09:19
#604 fixes this.

This issue is a duplicate of those marked in that pull request

**Closed** 2024-12-31 09:33 UTC
